name: flutter_store_listing
description: Flutter plugin to handle app reviews with SKStoreReviewController,
  generate app store links and open them for iOS or android.
version: 0.1.1+1
homepage: https://github.com/hpoul/flutter_store_listing

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  http: ">=0.12.0+2 <1.0.0"
  package_info: ">=0.4.0+4 <2.0.0"
  url_launcher: ">=5.0.3 <6.0.0"
  pedantic: ">=1.7.0 <2.0.0"
  logging: ">=0.11.3+2 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: design.codeux.flutter_store_listing
        pluginClass: FlutterStoreListingPlugin
      ios:
        pluginClass: FlutterStoreListingPlugin

